const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, '../data/MIE03_ADDRESS_MASTER_858.csv');
const outPath = path.join(__dirname, '../active/dashboard/data/address_master_map.js');

const csvData = fs.readFileSync(csvPath, 'utf8');
const lines = csvData.trim().split('\n');

const data = [];
for (let i = 1; i < lines.length; i++) {
  const values = lines[i].split(',');
  if (values.length >= 5) {
    data.push({
      rowId: Number(values[0].trim()),
      city_name: values[1].trim(),
      town_name: values[2].trim(),
      latitude: parseFloat(values[3].trim()),
      longitude: parseFloat(values[4].trim())
    });
  }
}

const outDir = path.dirname(outPath);
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}
const jsContent = `// Auto-generated by scripts/build_map_data.js
window.ADDRESS_MASTER_DATA = ${JSON.stringify(data)};
`;

fs.writeFileSync(outPath, jsContent, 'utf8');
console.log(`Generated ${outPath} with ${data.length} records.`);
